spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  security:
    user:
      name: user
      password: 1234

